//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oshopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int prodid { get; set; }
        public string productname { get; set; }
        public Nullable<int> proditeam { get; set; }
        public Nullable<int> Prodprice { get; set; }
    }
}
